### PR TITLE
Fix freezing of server threads during autocrafts

### LINKED ISSUE #19: Server hang
the server freezes when ordering a large number of autocraft resources
it only seems to happen on large networks
rs 2.2.6
https://pastebin.com/E8wMycrV

### PR DESCRIPTION
**Pull request by bigenergy**
Fix https://github.com/tth05/morerefinedstorage/issues/19

### CODE REVIEW

**Comment by tth05** [comment]
This won't be merged in this state. There are way too many unnecessary code style changes that have nothing to do with the actual "fix", which is just a weird workaround for an unknown problem. Just running the calculation on the main thread is not a fix.

**Comment by bigenergy** [comment]
> Just running the calculation on the main thread is not a fix.

However, this is a fix for me.

**Comment by tth05** [comment]
It's not a fix in the sense that it just works around the actual problem which might exist.

**Comment by bigenergy** [comment]
> It's not a fix in the sense that it just works around the actual problem which might exist.

Hi, did you manage to find the source of the problem?

**Comment by tth05** [comment]
> > It's not a fix in the sense that it just works around the actual problem which might exist.
> 
> Hi, did you manage to find the source of the problem?

Nope, never had it happen on my server or anyone else's server. Not sure how you managed to achieve that problem at all. My server has a system with billions of items in it, more than 20k items imported/exported per second and multiple huge crafting tasks being requested every second, but I've never had anything similar to this happen.

**Pull request closed without merging**
